### ISSUE TITLE
키보드에 툴바 추가하기

### ISSUE THREAD

**Issue by pjy0121** [ProjectInTheClass/OneshotTalk#17]
키보드에 화면 별로 저장, 복사, 내리기 등의 기능을 가진 툴바 추가

**Comment by dahunlee** [comment]
c994d26b361b31533716fa1cf0b18c01edbaf651
키보드에 각 화면 별 복사, 저장, 닫기 기능 툴바 추가 수정
기존 복사하기, 저장하기 버튼 삭제
아이콘 추가

**Comment by dahunlee** [comment]
c994d26b361b31533716fa1cf0b18c01edbaf651
키보드에 각 화면 별 복사, 저장, 닫기 기능 툴바 추가 수정
기존 복사하기, 저장하기 버튼 삭제
아이콘 추가
